### ISSUE TITLE
Create release of 2011 data for all countries

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#420]
Once tickets in v1.0 are completed, we need to create release of 2011 data for all countries.

**Comment by jwestw** [comment]
2011 data for:

- [ ] Population estimates (including age and sex)
- [ ] Population weighted centroids
- [ ] Disability data
- [ ] Urban/Rural Classification
- [ ] Bus Time table data (require sending an email) #430 
- [ ] Train time table data (require sending an email) #429 
- [ ] Bus/train stop location and status data (from Naptan) (require sending an email) #428

**Comment by paigeh1** [comment]
Population estimates are being resolved in #433 . Need to send email regarding bus/train timetable and bus/train stops
